language: python

env:
  global:
    - secure: "CvFj8Df5OiDRrW7EsTGhkltdmNlYerx9hH/tSKxiNFVDBUUFaTN7rUr7kWcOKchzerGwk7zjZ4SRXyoSCs+Srht6GZxWHkNROwKpp5Xvf5clbLXbp7GO1X/L5rLgrXpGwtkhgNuHx0X2IUCDHUQAUSumPgZcNFu3emgVxEqabN0="

matrix:
  allow_failures:
    - env: "TOX_ENV=docs-linkcheck"
  include:
    - env: TOX_ENV=lint
      python: 3.6
    - env: TOX_ENV=py27
      python: 2.7
    - env: TOX_ENV=py36
      python: 3.6
    - env: TOX_ENV=pypy
      python: 3.6
    - env: TOX_ENV=docs
      python: 3.6
    - env: TOX_ENV=apidocs
      python: 2.7
    - env: TOX_ENV=docs-spellcheck
      python: 3.6
    - env: TOX_ENV=docs-linkcheck
      python: 3.6
    # - PUSH_DOCS=true

install:
  - ./.travis/install.sh

script:
  - if [[ -n "${TOX_ENV}" ]]; then tox -e $TOX_ENV; fi
  - if [[ "$PUSH_DOCS" == "true" ]]; then ./.travis/build_docs.sh; fi


after_success:
  - if [[ "${TOX_ENV:0:2}" == 'py' ]]; then coverage combine; coveralls; fi

notifications:
  irc:
    channels: "chat.freenode.net#twisted-dev"
    template:
      - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
    use_notice: true

branches:
  only:
    - master
    - gh-pages
